services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clicknext-backend
    ports:
      - "${SERVER_ADDRESS}:${SERVER_ADDRESS}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  db:
    image: postgres:16
    container_name: clicknext-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      retries: 5
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
