CREATE TABLE IF NOT EXISTS boards (
    board_id SERIAL PRIMARY KEY ,
    title VARCHAR(255) NOT NULL ,
    description VARCHAR(255),
    created_by INT NOT NULL ,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (created_by) REFERENCES users (user_id)
);